# Generated by Django 5.0.1 on 2024-01-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimalClassification",
            fields=[
                (
                    "animal_classification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("kingdom_name", models.CharField(max_length=250)),
                ("species", models.CharField(max_length=250)),
                ("number_of_species", models.IntegerField(default=1, null=True)),
                ("animal_class", models.CharField(max_length=250)),
                ("order", models.CharField(max_length=250)),
                ("domestic", models.BooleanField(default=False)),
                ("wild_animal", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "animal_id",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("english_name", models.CharField(max_length=250)),
                ("scientific_name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("areas_in_Uganda", models.CharField(max_length=250)),
                ("known_values", models.TextField()),
                ("value_details", models.TextField()),
                ("unique_habitat", models.CharField(max_length=250)),
                ("toxicity_to_humans", models.CharField(max_length=250)),
                ("diet", models.CharField(max_length=250)),
                ("behavior", models.CharField(max_length=250)),
                ("habitat_impact", models.CharField(max_length=250)),
                ("conservation_status", models.CharField(max_length=250)),
                ("conservation_measures", models.CharField(max_length=250)),
                ("reproduction", models.CharField(max_length=250)),
                ("gestation_period", models.CharField(max_length=250)),
                ("life_span", models.CharField(max_length=250)),
                ("predators", models.TextField()),
                ("prey", models.TextField()),
                ("ethical_medicinal_uses", models.TextField()),
                ("threats", models.TextField()),
                ("notes", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="animal_images"),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="animal_videos"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="animal_audios"),
                ),
                ("citation", models.TextField()),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                (
                    "animal_classifications",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="animals.animalclassification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalLocalName",
            fields=[
                (
                    "animal_local_name_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("local_name", models.CharField(max_length=250)),
                ("language", models.CharField(max_length=250)),
                (
                    "animal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animals.animal",
                    ),
                ),
            ],
        ),
    ]
