# Generated by Django 5.0.1 on 2024-01-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CulturalKingdom",
            fields=[
                (
                    "cultural_kingdom_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("kingdom_name", models.CharField(max_length=250)),
                (
                    "title_of_leader",
                    models.CharField(
                        blank=True,
                        choices=[("king", "King"), ("chief", "Chief")],
                        max_length=250,
                        null=True,
                    ),
                ),
                ("number_of_clans", models.IntegerField(default=1, null=True)),
                (
                    "leader_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "contributor_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("citation", models.TextField(blank=True, null=True)),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EthnicGroup",
            fields=[
                (
                    "ethnic_group_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "ethnic_group_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "region_in_Uganda",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "number_of_ethnicity",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("number_of_languages", models.IntegerField(default=1, null=True)),
                (
                    "number_of_kingdoms_or_chiefdoms",
                    models.IntegerField(default=1, null=True),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to="ethnic_group_audio"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "contributor_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("citation", models.TextField(blank=True, null=True)),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ethnicity",
            fields=[
                (
                    "ethnicity_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("ethnicity_name", models.CharField(max_length=250, unique=True)),
                (
                    "region_in_Uganda",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=250, null=True)),
                ("common_food_types", models.TextField(blank=True, null=True)),
                (
                    "staple_food",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "staple_food_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ethnicity_images/"
                    ),
                ),
                ("cuisines", models.TextField(blank=True, null=True)),
                (
                    "main_cash_crop",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "main_cash_crop_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ethnicity_images/"
                    ),
                ),
                ("leisure_activities", models.TextField(blank=True, null=True)),
                ("entertainment_activities", models.TextField(blank=True, null=True)),
                ("denominations", models.TextField(blank=True, null=True)),
                ("universal_rituals", models.TextField(blank=True, null=True)),
                ("ceremonies", models.TextField(blank=True, null=True)),
                (
                    "contributor_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("citation", models.TextField(blank=True, null=True)),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                ("clan_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("clan_name", models.CharField(blank=True, max_length=250)),
                ("clan_seat", models.CharField(blank=True, max_length=250)),
                ("clan_anthem", models.TextField(blank=True, null=True)),
                ("clan_roles", models.TextField(blank=True, null=True)),
                (
                    "totem_image",
                    models.ImageField(blank=True, null=True, upload_to="clan_images"),
                ),
                ("totem", models.CharField(blank=True, max_length=250)),
                ("secondary_totem", models.CharField(blank=True, max_length=250)),
                ("clan_history", models.TextField(blank=True)),
                ("clan_leader_title", models.CharField(blank=True, max_length=250)),
                ("clan_leader_name", models.CharField(blank=True, max_length=250)),
                ("cultural_sites", models.TextField(blank=True)),
                ("male_names", models.TextField(blank=True)),
                ("female_names", models.TextField(blank=True)),
                ("reserved_male_names", models.TextField(blank=True)),
                ("reserved_female_names", models.TextField(blank=True)),
                ("taboos", models.TextField(blank=True)),
                ("lead_god", models.CharField(blank=True, max_length=250)),
                ("other_gods", models.CharField(blank=True, max_length=250)),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to="ethnic_group_audio"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "contributor_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("citation", models.TextField(blank=True, null=True)),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                (
                    "ethnicity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cultures.ethnicity",
                    ),
                ),
            ],
        ),
    ]
