# Generated by Django 5.0.1 on 2024-01-17 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cultures", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clan",
            unique_together={("clan_name", "ethnicity_name")},
        ),
        migrations.RemoveField(
            model_name="clan",
            name="specific_rituals",
        ),
    ]
