# Generated by Django 5.0.1 on 2024-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cultures", "0002_alter_clan_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clan",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="clan",
            name="ethnicity_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
