# Generated by Django 5.0.1 on 2024-01-19 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cultures", "0004_remove_clan_ethnicity_name_clan_ethnicity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="culturalkingdom",
            old_name="cultural_kingdom",
            new_name="cultural_kingdom_id",
        ),
    ]
