# Generated by Django 4.2.9 on 2024-01-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fgfuser",
            name="is_contributor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fgfuser",
            name="is_masteruser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fgfuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
