# Generated by Django 4.2.9 on 2024-01-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_fgfuser_is_contributor_fgfuser_is_masteruser_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="fgfuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="fgfuser",
            name="is_contributor",
        ),
        migrations.RemoveField(
            model_name="fgfuser",
            name="is_masteruser",
        ),
        migrations.AlterField(
            model_name="fgfuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
