# Generated by Django 4.2.9 on 2024-01-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_alter_fgfuser_managers_remove_fgfuser_is_contributor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fgfuser",
            name="is_contributor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fgfuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fgfuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
