# Generated by Django 4.2.9 on 2024-01-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_fgfuser_is_contributor_fgfuser_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fgfuser",
            name="is_masteruser",
            field=models.BooleanField(default=False),
        ),
    ]
