# Generated by Django 5.0.1 on 2024-01-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="langauge_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="medicinalplant",
            name="medicinal_plant_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="medicinalplantimagegallery",
            name="medicinal_plant_image_gallery_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="medicinalplantname",
            name="medicinal_plant_name_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="plant",
            name="plant_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="plantimagegallery",
            name="plant_image_gallery_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="plantname",
            name="plant_name_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="scientificclarification",
            name="scientific_clarification_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
