# Generated by Django 4.2.9 on 2024-01-21 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scientificclarification",
            name="plant",
        ),
    ]
