# Generated by Django 5.0.1 on 2024-01-15 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fgfAuth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="master",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="master",
            name="last_name",
        ),
    ]
