# Generated by Django 5.0.1 on 2024-01-16 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fgfAuth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="fgfuser",
            managers=[],
        ),
    ]
